### ISSUE TITLE
Cannot use jxls with Spring Boot 3.x

### ISSUE THREAD

**Issue by klacia** [jxlsteam/jxls#268]
I wanted to upgrade my app to spring boot 3.X. Spring boot uses [logback 1.4](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes). Logback 1.4 is incompatible with logback 1.2 that jxls is using. 

Do you plan to update jxls dependencies to Java 11 and logback 1.4?

**Comment by leonate** [comment]
I guess this is a question whether we are ready to drop the support for JDK 8.
Btw, have you tried to use logback 1.4 with jxls (e.g. by using Maven exclusions)? What does it say? Are there any breaking API changes between 1.4 and 1.2 that are used in jxls ?

**Comment by klacia** [comment]
Yes, I tried to exclude version from jxls. I got this: 

`
java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/GenericConfigurator
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.jxls.builder.xml.XmlAreaBuilder.build(XmlAreaBuilder.java:71)
	at org.jxls.builder.xml.XmlAreaBuilder.build(XmlAreaBuilder.java:89)
`

**Comment by leonate** [comment]
I see. So it looks like it is a question of releasing a version of Jxls without JDK 8 support and with an upgraded logback 1.4. Theoretically we could also replace the logback usages with some other alternative but it will not be that easy since it is used not just for logging but also for some XML processing.
@SoltauFintel , what do you think about dropping a support for JDK 8 to make JDK 11 the lowest supported java version?

**Comment by gastendonk** [comment]
@leonate

33% still use Java 8. Same in our company (33% of our clients use Java 8).

We can consider 2.14.0 as first Java 11 version. And if there are still Java 8 requirements, we would have to release them as 2.13.x.

**Comment by klacia** [comment]
Do you have an ETA for this issue?
