### ISSUE TITLE
使用SXSS功能。无法正常使用mergeCells函数。

### ISSUE THREAD

**Issue by bole915226051** [jxlsteam/jxls#274]
最新的代码，在`IssueB160Test`中。
1、将`xlsArea.applyAt(new CellRef("Result!A1"), context);`
修改为`xlsArea.applyAt(new CellRef("Template!A1"), context);`
2、将`IssueB160Test.xlsx`中`A1`的批注修改为
```
Author:
jx:area(lastCell="E7")
jx:mergeCells(lastCell="A1",cols="2")
```
```
java.lang.IllegalArgumentException: Attempting to write a row[0] in the range [0,5] that is already written to disk.

	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:132)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:61)
	at org.jxls.transform.poi.PoiTransformer.mergeCells(PoiTransformer.java:649)
	at org.jxls.command.MergeCellsCommand.applyAt(MergeCellsCommand.java:91)
	at org.jxls.area.XlsArea.applyAt(XlsArea.java:182)
	at org.jxls.templatebasedtests.IssueB160Test.test(IssueB160Test.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

**Comment by SoltauFintel** [comment]
Please write in English.
