### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by nguacon90** [jxlsteam/jxls#59]
I've used jxls version 2.6.0 to stream data to excel xlsx file. The problem is **GC overhead limit exceeded** as below:
```
nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded] with root cause
java.lang.OutOfMemoryError: GC overhead limit exceeded 
        at java.util.Arrays.copyOf(Arrays.java:3181) ~[?:1.8.0_265]
        at java.util.ArrayList.grow(ArrayList.java:267) ~[?:1.8.0_265]
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241) ~[?:1.8.0_265]
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233) ~[?:1.8.0_265]
        at java.util.ArrayList.add(ArrayList.java:464) ~[?:1.8.0_265]
        at org.apache.xmlbeans.impl.store.Xobj.find_all_element_users(Xobj.java:2098) ~[spring-batch-excel-0.5.4.jar!/:?]
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTColsImpl.getColArray(Unknown Source) ~[spring-batch-excel-0.5.4.jar!/:?]
        at org.apache.poi.xssf.usermodel.helpers.ColumnHelper.getColumn1Based(ColumnHelper.java:187) ~[spring-batch-excel-0.5.4.jar!/:?]
        at org.apache.poi.xssf.usermodel.helpers.ColumnHelper.getOrCreateColumn1Based(ColumnHelper.java:285) ~[spring-batch-excel-0.5.4.jar!/:?]
        at org.apache.poi.xssf.usermodel.helpers.ColumnHelper.setColWidth(ColumnHelper.java:271) ~[spring-batch-excel-0.5.4.jar!/:?]
        at org.apache.poi.xssf.usermodel.XSSFSheet.setColumnWidth(XSSFSheet.java:2559) ~[spring-batch-excel-0.5.4.jar!/:?]
        at org.jxls.transform.poi.PoiTransformer.transformCell(PoiTransformer.java:190) ~[jxls-poi-1.2.0.jar!/:?]
        at org.jxls.transform.poi.PoiTransformer.transform(PoiTransformer.java:172) ~[jxls-poi-1.2.0.jar!/:?]
        at org.jxls.area.XlsArea.transformTopStaticArea(XlsArea.java:393) ~[jxls-2.6.0.jar!/:?]
        at org.jxls.area.XlsArea.applyAt(XlsArea.java:159) ~[jxls-2.6.0.jar!/:?]
        at org.jxls.command.EachCommand.processCollection(EachCommand.java:309) ~[jxls-2.6.0.jar!/:?]
        at org.jxls.command.EachCommand.applyAt(EachCommand.java:265) ~[jxls-2.6.0.jar!/:?]
        at org.jxls.area.XlsArea.applyAt(XlsArea.java:171) ~[jxls-2.6.0.jar!/:?]
        at org.jxls.command.EachCommand.processCollection(EachCommand.java:309) ~[jxls-2.6.0.jar!/:?]
        at org.jxls.command.EachCommand.applyAt(EachCommand.java:265) ~[jxls-2.6.0.jar!/:?]
        at org.jxls.area.XlsArea.applyAt(XlsArea.java:171) ~[jxls-2.6.0.jar!/:?]
```

My question is the problem cause by jxls or not? Any one can help me to resolve it?
Thanks a lot.

**Comment by SoltauFintel** [comment]
I've tested streaming with the maximum of 1,000,000 rows. However, never with 500 columns.

What `-Xmx` value do you use? Have you tried to increase the memory?

The line `org.apache.poi.xssf.usermodel.XSSFSheet.setColumnWidth(XSSFSheet.java:2559)` looks a bit like non-streaming. But I haven't checked that yet.

What JXLS FormulaProcessor do you use?

Please add the template XLSX.

**Comment by nguacon90** [comment]
MyTemplate excel: [https://drive.google.com/file/d/16ZqzuMCSW2TaQ_BE00EODfwLuCCI_JOl/view?usp=sharing](url).
Sale quantity of each warehouse have been rendered by date, also can be over 500 columns if period over 1 years and many warehouses.
Thanks.

**Comment by SoltauFintel** [comment]
Please try ignoreColumnProps. (see above)

**Comment by nguacon90** [comment]
I tried but error still occurs:
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.poi.xssf.usermodel.XSSFCell.setBlank(XSSFCell.java:943) ~[spring-batch-excel-0.5.4.jar:?]
	at org.apache.poi.xssf.usermodel.XSSFCell.setCellType(XSSFCell.java:1017) ~[spring-batch-excel-0.5.4.jar:?]
	at org.apache.poi.xssf.usermodel.XSSFCell.setCellType(XSSFCell.java:970) ~[spring-batch-excel-0.5.4.jar:?]
	at org.jxls.transform.poi.PoiTransformer.transformCell(PoiTransformer.java:200) ~[jxls-poi-1.2.0.jar:?]
	at org.jxls.transform.poi.PoiTransformer.transform(PoiTransformer.java:172) ~[jxls-poi-1.2.0.jar:?]
	at org.jxls.area.XlsArea.transformTopStaticArea(XlsArea.java:393) ~[jxls-2.6.0.jar:?]
	at org.jxls.area.XlsArea.applyAt(XlsArea.java:159) ~[jxls-2.6.0.jar:?]
	at org.jxls.command.EachCommand.processCollection(EachCommand.java:309) ~[jxls-2.6.0.jar:?]
	at org.jxls.command.EachCommand.applyAt(EachCommand.java:265) ~[jxls-2.6.0.jar:?]
	at org.jxls.area.XlsArea.applyAt(XlsArea.java:171) ~[jxls-2.6.0.jar:?]
	at org.jxls.command.EachCommand.processCollection(EachCommand.java:309) ~[jxls-2.6.0.jar:?]
	at org.jxls.command.EachCommand.applyAt(EachCommand.java:265) ~[jxls-2.6.0.jar:?]
	at org.jxls.area.XlsArea.applyAt(XlsArea.java:171) ~[jxls-2.6.0.jar:?]
	at org.jxls.util.JxlsHelper.processTemplate(JxlsHelper.java:200) ~[jxls-2.6.0.jar:?]
```

**Comment by SoltauFintel** [comment]
Your template is a .xls file. Do you really use XLSX as template file format?

**Comment by nguacon90** [comment]
Yes. I used. However when change to Xls. Can render excel file, however limited columns error occurs.

**Comment by SoltauFintel** [comment]
I don't understand.

**Comment by nguacon90** [comment]
Me too. Only error occurs with template .xlsx. if using .xls still generate file excel however document not full fill data of columns. For example document expected 300 columns but file render only 256 columns that maximum column .xls support by microsoft. :)

**Comment by SoltauFintel** [comment]
;-)  I said: I don't understand what you're writing.

**Comment by nguacon90** [comment]
if using xls template, only rendering 256 columns that maximum column support by microsoft excel. You can see on this link [https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_other-mso_2010/what-is-the-maximum-number-of-columns-in-a/5a053135-4865-e011-8dfc-68b599b31bf5#:~:text=In%20an%20Excel%2097%2D2003,xlsm%20or%20.](url).
